/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';


const up_arrow_1 = 'assets/images/icons/up-arrow_1.svg';
const up_arrow_2 = 'assets/images/icons/up-arrow_2.svg';
const home_location = 'assets/images/icons/home-location.svg';
const corner = 'assets/images/icons/corner.svg';
const farm_house = 'assets/images/icons/farm-house.svg';
const gate = 'assets/images/icons/gate.svg';
const ranch_gate = 'assets/images/icons/ranch-gate.svg';
const traffic_light_red = 'assets/images/icons/traffic-light-red.svg';
const traffic_light_orange = 'assets/images/icons/traffic-light-orange.svg';
const traffic_light_green = 'assets/images/icons/traffic-light-green.svg';
const camera = 'assets/images/icons/camera.svg';
const gallery = 'assets/images/icons/gallery.svg';
const bridge = 'assets/images/icons/bridge.svg';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData up_arrow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
